### ISSUE TITLE
collector_sidecar.yml template prevents sidecar from starting: config sytax is incorrect

### ISSUE THREAD

**Issue by brettfire** [mklettner/ansible-role-graylog-collector#2]
https://github.com/mklettner/ansible-role-graylog-collector/blob/32e3de7423546878aebe5d7c94e8ac93ed7d8cc2/templates/collector_sidecar.yml#L18

With collector sidecar v 0.1.8, the sidecar will not start with the config being written to `/etc/graylog/collector-sidecar/collector_sidecar.yml` as it is by this role. I'm not sure if this ever worked, but it sure is not working for me. The fix is to remove the yaml multiline string and fix the indentation like so:
```
...
log_rotation_time: {{sidecar_log_rotation_time}}
log_max_age: {{sidecar_log_max_age}}
tags:
{% for tag in sidecar_tags %}
  - {{ tag }}
{% endfor %}

backends:
{% for backend in sidecar_backends %}
  - name: {{ backend.name }}
    enabled: {{ backend.enabled }}
    binary_path: {{ backend.binary_path }}
    configuration_path: {{ backend.configuration_path }}
{% endfor %}

**Comment by mklettner** [comment]
Thx for reporting this issue. I was able to reproduce it and it was indeed not working anymore.
Fixed and tested it with your suggestion.
